FROM prestashop/prestashop:9.0.x-apache

ARG cert_path
ENV CERT_PATH=$cert_path

ARG cert_key_path
ENV CERT_KEY_PATH=$cert_key_path

RUN apt update && apt install -y vim curl unzip

# COMPOSER - Install Composer globally
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer --version

# XDEBUG
# RUN pecl install xdebug-3.4.2 \
#       && docker-php-ext-enable xdebug
# RUN echo zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20240924/xdebug.so >> /usr/local/etc/php/php.ini

# APACHE
COPY apache/default.conf /etc/apache2/sites-available/000-default.conf
COPY apache/ssl-params.conf /etc/apache2/conf-available/ssl-params.conf
COPY apache/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf
RUN a2enmod ssl
RUN a2enmod headers
RUN a2ensite default-ssl
RUN a2enconf ssl-params
